/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './bootstrap-growl.module';
import * as i2 from '@angular/common';
import * as i3 from './bootstrap-growl.service';
export const BootstrapGrowlModuleNgFactory:i0.NgModuleFactory<i1.BootstrapGrowlModule> = i0.ɵcmf(i1.BootstrapGrowlModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i3.BootstrapGrowlService,
          i3.BootstrapGrowlService,([] as any[])),i0.ɵmpd(512,i2.CommonModule,i2.CommonModule,
          ([] as any[])),i0.ɵmpd(512,i1.BootstrapGrowlModule,i1.BootstrapGrowlModule,
          ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvd2VsY29tZS9Eb2N1bWVudHMvR2l0SHViL25neC1ib290c3RyYXAtZ3Jvd2wvc3JjL2Jvb3RzdHJhcC1ncm93bC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvd2VsY29tZS9Eb2N1bWVudHMvR2l0SHViL25neC1ib290c3RyYXAtZ3Jvd2wvc3JjL2Jvb3RzdHJhcC1ncm93bC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
