/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './bootstrap-growl.component';
import * as i3 from './bootstrap-growl.service';
const styles_BootstrapGrowlComponent:any[] = ([] as any[]);
export const RenderType_BootstrapGrowlComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_BootstrapGrowlComponent,data:{}});
function View_BootstrapGrowlComponent_2(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),4,'button',[['class',
      'close'],['data-dismiss','alert'],['type','button']],(null as any),[[(null as any),
      'click']],(_v,en,$event) => {
    var ad:boolean = true;
    var _co:any = _v.component;
    if (('click' === en)) {
      const pd_0:any = ((<any>_co.closeAlert((<any>_v.parent).context.$implicit)) !== false);
      ad = (pd_0 && ad);
    }
    return ad;
  },(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),['\n            '])),
      (_l()(),i0.ɵeld(2,0,(null as any),(null as any),1,'span',[['aria-hidden','true']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['×'])),(_l()(),i0.ɵted(-1,(null as any),['\n          ']))],
      (null as any),(null as any));
}
function View_BootstrapGrowlComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),11,'div',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵeld(2,0,(null as any),
      (null as any),8,'div',[['role','alert']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),i0.ɵdid(3,278528,(null as any),0,i1.NgClass,[i0.IterableDiffers,
      i0.KeyValueDiffers,i0.ElementRef,i0.Renderer],{klass:[0,'klass'],ngClass:[1,
      'ngClass']},(null as any)),i0.ɵpod(4,{'alert-dismissible':0}),(_l()(),i0.ɵted(-1,
      (null as any),['\n          '])),(_l()(),i0.ɵand(16777216,(null as any),(null as any),
      1,(null as any),View_BootstrapGrowlComponent_2)),i0.ɵdid(7,16384,(null as any),
      0,i1.NgIf,[i0.ViewContainerRef,i0.TemplateRef],{ngIf:[0,'ngIf']},(null as any)),
      (_l()(),i0.ɵted(-1,(null as any),['\n          '])),(_l()(),i0.ɵeld(9,0,(null as any),
          (null as any),0,'span',([] as any[]),[[8,'innerHTML',1]],(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),['\n        '])),
      (_l()(),i0.ɵted(-1,(null as any),['\n    ']))],(_ck,_v) => {
    const currVal_0:any = i0.ɵinlineInterpolate(1,'alert alert-',_v.context.$implicit.type,
        '');
    const currVal_1:any = _ck(_v,4,0,_v.context.$implicit.dismissable);
    _ck(_v,3,0,currVal_0,currVal_1);
    const currVal_2:any = _v.context.$implicit.dismissable;
    _ck(_v,7,0,currVal_2);
  },(_ck,_v) => {
    const currVal_3:any = _v.context.$implicit.message;
    _ck(_v,9,0,currVal_3);
  });
}
export function View_BootstrapGrowlComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵand(16777216,(null as any),(null as any),1,(null as any),
      View_BootstrapGrowlComponent_1)),i0.ɵdid(1,802816,(null as any),0,i1.NgForOf,
      [i0.ViewContainerRef,i0.TemplateRef,i0.IterableDiffers],{ngForOf:[0,'ngForOf']},
      (null as any))],(_ck,_v) => {
    var _co:i2.BootstrapGrowlComponent = _v.component;
    const currVal_0:any = _co.alerts;
    _ck(_v,1,0,currVal_0);
  },(null as any));
}
export function View_BootstrapGrowlComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'bootstrap-growl',
      ([] as any[]),(null as any),(null as any),(null as any),View_BootstrapGrowlComponent_0,
      RenderType_BootstrapGrowlComponent)),i0.ɵdid(1,114688,(null as any),0,i2.BootstrapGrowlComponent,
      [i3.BootstrapGrowlService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const BootstrapGrowlComponentNgFactory:i0.ComponentFactory<i2.BootstrapGrowlComponent> = i0.ɵccf('bootstrap-growl',
    i2.BootstrapGrowlComponent,View_BootstrapGrowlComponent_Host_0,{alertCount:'alertCount',
        autoClose:'autoClose'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvd2VsY29tZS9Eb2N1bWVudHMvR2l0SHViL25neC1ib290c3RyYXAtZ3Jvd2wvc3JjL2Jvb3RzdHJhcC1ncm93bC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvd2VsY29tZS9Eb2N1bWVudHMvR2l0SHViL25neC1ib290c3RyYXAtZ3Jvd2wvc3JjL2Jvb3RzdHJhcC1ncm93bC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy93ZWxjb21lL0RvY3VtZW50cy9HaXRIdWIvbmd4LWJvb3RzdHJhcC1ncm93bC9zcmMvYm9vdHN0cmFwLWdyb3dsLmNvbXBvbmVudC50cy5Cb290c3RyYXBHcm93bENvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvd2VsY29tZS9Eb2N1bWVudHMvR2l0SHViL25neC1ib290c3RyYXAtZ3Jvd2wvc3JjL2Jvb3RzdHJhcC1ncm93bC5jb21wb25lbnQudHMuQm9vdHN0cmFwR3Jvd2xDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2ICpuZ0Zvcj1cImxldCBhbGVydCBvZiBhbGVydHNcIj5cbiAgICAgICAgPGRpdiBjbGFzcz1cImFsZXJ0IGFsZXJ0LXt7YWxlcnQudHlwZX19XCIgW25nQ2xhc3NdPVwieydhbGVydC1kaXNtaXNzaWJsZSc6IGFsZXJ0LmRpc21pc3NhYmxlfVwiIHJvbGU9XCJhbGVydFwiPlxuICAgICAgICAgIDxidXR0b24gdHlwZT1cImJ1dHRvblwiIGNsYXNzPVwiY2xvc2VcIiBkYXRhLWRpc21pc3M9XCJhbGVydFwiIChjbGljayk9XCJjbG9zZUFsZXJ0KGFsZXJ0KVwiICpuZ0lmPVwiYWxlcnQuZGlzbWlzc2FibGVcIj5cbiAgICAgICAgICAgIDxzcGFuIGFyaWEtaGlkZGVuPVwidHJ1ZVwiPiZ0aW1lczs8L3NwYW4+XG4gICAgICAgICAgPC9idXR0b24+XG4gICAgICAgICAgPHNwYW4gW2lubmVySHRtbF09XCJhbGVydC5tZXNzYWdlXCI+PC9zcGFuPlxuICAgICAgICA8L2Rpdj5cbiAgICA8L2Rpdj4iLCI8Ym9vdHN0cmFwLWdyb3dsPjwvYm9vdHN0cmFwLWdyb3dsPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDRVU7TUFBQTtNQUFBO0lBQUE7SUFBQTtJQUF5RDtNQUFBO01BQUE7SUFBQTtJQUF6RDtFQUFBLGdDQUErRztNQUM3RztVQUFBO01BQXlCLHlDQUFjOzs7O29CQUhuRDtNQUFBLHdFQUFrQzthQUFBLG1DQUMxQjtNQUFBO01BQUEscUNBQUE7a0RBQUE7TUFBQSxrQ0FBd0MsNEJBQWtFO01BQUEsaUNBQ3hHO01BQUEsd0RBQUE7TUFBQTtNQUVTLG9EQUNUO1VBQUE7VUFBQSw4QkFBeUM7TUFDckM7SUFMRDtRQUFBO0lBQW1DO0lBQXhDLFdBQUssVUFBbUMsU0FBeEM7SUFDdUY7SUFBckYsV0FBcUYsU0FBckY7O0lBR007SUFBTixXQUFNLFNBQU47Ozs7b0JBTFY7TUFBQSx3Q0FBQTtNQUFBO01BQUE7O0lBQUs7SUFBTCxXQUFLLFNBQUw7Ozs7b0JDQUE7TUFBQTt3Q0FBQSxVQUFBO01BQUE7SUFBQTs7Ozs7In0=
